// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAlertCalloutStyles() {
  return window['go']['main']['App']['GetAlertCalloutStyles']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function LoadAndDisplayMarkdown(arg1) {
  return window['go']['main']['App']['LoadAndDisplayMarkdown'](arg1);
}

export function PrintContent() {
  return window['go']['main']['App']['PrintContent']();
}

export function PrintContentToPDF() {
  return window['go']['main']['App']['PrintContentToPDF']();
}

export function ReloadCurrentDocument() {
  return window['go']['main']['App']['ReloadCurrentDocument']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSettingsSessionOnly(arg1) {
  return window['go']['main']['App']['SaveSettingsSessionOnly'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}
