// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetArgs():Promise<Array<string>>;

export function ProcessMarkdown(arg1:string):Promise<string>;
