// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDocClass(arg1) {
  return window['go']['main']['App']['AddDocClass'](arg1);
}

export function ConvertMarkdownToHTML(arg1) {
  return window['go']['main']['App']['ConvertMarkdownToHTML'](arg1);
}

export function CreateGoldmarkInstance() {
  return window['go']['main']['App']['CreateGoldmarkInstance']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function LoadAndDisplayMarkdown(arg1) {
  return window['go']['main']['App']['LoadAndDisplayMarkdown'](arg1);
}

export function OpenFileMenuHandler(arg1) {
  return window['go']['main']['App']['OpenFileMenuHandler'](arg1);
}

export function PrintContent() {
  return window['go']['main']['App']['PrintContent']();
}

export function PrintContentToPDF() {
  return window['go']['main']['App']['PrintContentToPDF']();
}

export function RemoveDocClass(arg1) {
  return window['go']['main']['App']['RemoveDocClass'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function ToggleDocClass(arg1) {
  return window['go']['main']['App']['ToggleDocClass'](arg1);
}
