// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {goldmark} from '../models';
import {menu} from '../models';

export function AddDocClass(arg1:Array<string>):Promise<void>;

export function ConvertMarkdownToHTML(arg1:Array<number>):Promise<Array<number>>;

export function CreateGoldmarkInstance():Promise<goldmark.Markdown>;

export function GetTheme():Promise<string>;

export function LoadAndDisplayMarkdown(arg1:string):Promise<void>;

export function OpenFileMenuHandler(arg1:menu.CallbackData):Promise<void>;

export function PrintContent():Promise<void>;

export function PrintContentToPDF():Promise<void>;

export function RemoveDocClass(arg1:Array<string>):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function ToggleDocClass(arg1:Array<string>):Promise<void>;
